# DB 테이블을 DataFrame 읽어오기

SELECT 결과 -> DataFrame

- 예제 데이터베이스 : MySQL 샘플dB (sakila, world)
- 설치 패키지
    - pymysql
    - SqlAlchemy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from sqlalchemy import create_engine

Matplotlib is building the font cache; this may take a moment.

In [3]:
engine = create_engine("mysql+pymysql://root:1234@localhost/sakila?charset=utf8")

In [4]:
pd.read_sql("SHOW TABLES;", engine)

              Tables_in_sakila
0                        actor
1                   actor_info
2                      address
3                     category
4                         city
5                      country
6                     customer
7                customer_list
8                         film
9                   film_actor
10               film_category
11                   film_list
12                   film_text
13                   inventory
14                    language
15  nicer_but_slower_film_list
16                     payment
17                      rental
18      sales_by_film_category
19              sales_by_store
20                       staff
21                  staff_list
22                       store

In [5]:
SQL_QUERY = """
    SELECT * FROM customer
"""

df_customer = pd.read_sql(SQL_QUERY, engine)
df_customer

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20
...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37,2006-02-15 04:57:20
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37,2006-02-15 04:57:20
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37,2006-02-15 04:57:20
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37,2006-02-15 04:57:20
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37,2006-02-15 04:57:20

In [6]:
SQL_QUERY = """
    SELECT * FROM payment
"""

df_payment = pd.read_sql(SQL_QUERY, engine)
df_payment

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37,2006-02-15 22:12:30
1,2,1,1,573,0.99,2005-05-28 10:35:23,2006-02-15 22:12:30
2,3,1,1,1185,5.99,2005-06-15 00:54:12,2006-02-15 22:12:30
3,4,1,2,1422,0.99,2005-06-15 18:02:53,2006-02-15 22:12:30
4,5,1,2,1476,9.99,2005-06-15 21:08:46,2006-02-15 22:12:30
...,...,...,...,...,...,...,...
16039,16045,599,1,14599,4.99,2005-08-21 17:43:42,2006-02-15 22:24:12
16040,16046,599,1,14719,1.99,2005-08-21 21:41:57,2006-02-15 22:24:12
16041,16047,599,2,15590,8.99,2005-08-23 06:09:44,2006-02-15 22:24:12
16042,16048,599,2,15719,2.99,2005-08-23 11:08:46,2006-02-15 22:24:13
16043,16049,599,2,15725,2.99,2005-08-23 11:25:00,2006-02-15 22:24:13

In [8]:
df_payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 16044 entries, 0 to 16043
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   payment_id    16044 non-null  int64
 1   customer_id   16044 non-null  int64
 2   staff_id      16044 non-null  int64
 3   rental_id     16044 non-null  int64
 4   amount        16044 non-null  float64
 5   payment_date  16044 non-null  datetime64[us]
 6   last_update   16044 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(4)
memory usage: 877.5 KB

# 특정 DB의 내용을 CSV로 저장

In [11]:
dbname = 'sakila'

engine = create_engine(f"mysql+pymysql://root:1234@localhost/{dbname}?charset=utf8")

dataset_path = r'/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset'

path = os.path.join(dataset_path, 'mysql', dbname)
if not os.path.exists(path):
    print(path, '를 생성합니다')
    os.makedirs(path)

table_names = pd.read_sql('SHOW TABLES', engine).iloc[:, 0]    

for table_name in table_names:
    query = f"SELECT * FROM {table_name}"
    table_df = pd.read_sql(query, engine)

    # DB -> DataFrame -> CSV 저장
    csv_path = os.path.join(dataset_path, 'mysql', dbname, f'{table_name}.csv')

    table_df.to_csv(csv_path, index=False, encoding='utf8')
    print(f'{csv_path} 생성')

engine.dispose()  # 연결 닫기

/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/actor.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/actor_info.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/address.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/category.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/city.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/country.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/customer.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/customer_list.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/film.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/film_actor.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/film_category.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/film_list.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/film_text.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/inventory.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/language.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/nicer_but_slower_film_list.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/payment.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/rental.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/sales_by_film_category.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/sales_by_store.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/staff.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/staff_list.csv 생성
/Users/leo/LeoData/MyCode/KoreaITAcademy/LangChain/dataset/mysql/sakila/store.csv 생성